feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  rabbitmq:
      host: 106.52.64.17
      virtual-host: /java1907
      username: java1907
      password: 123456
